# Generated by Django 4.1.2 on 2023-08-20 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0002_remove_stock_buying_price_remove_stock_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', models.FloatField()),
                ('change', models.FloatField()),
                ('volume', models.IntegerField()),
                ('market_cap', models.BigIntegerField()),
                ('selling_price', models.FloatField()),
                ('buying_price', models.FloatField()),
                ('is_notifying', models.IntegerField()),
                ('update_perid', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
