# Generated by Django 4.2.2 on 2023-09-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_users', '0002_rename_update_perid_stockuser_update_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockuser',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockuser',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
