# Generated by Django 4.2.2 on 2023-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_users', '0004_alter_stockuser_change_alter_stockuser_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockuser',
            name='change',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
