# Generated by Django 4.2.2 on 2023-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_users', '0005_alter_stockuser_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
