# Generated by Django 4.2.2 on 2023-09-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_users', '0006_stockuser_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockuser',
            name='change',
        ),
        migrations.RemoveField(
            model_name='stockuser',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='stockuser',
            name='volume',
        ),
    ]
