# Generated by Django 4.2.2 on 2023-09-27 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_users', '0008_stockuser_last_price_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockuser',
            name='last_price_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
