# Generated by Django 4.2.2 on 2023-09-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField()),
                ('sector', models.CharField(max_length=100)),
            ],
        ),
    ]
