# Generated by Django 4.2.2 on 2023-06-11 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('close', models.FloatField()),
                ('change', models.FloatField()),
                ('volume', models.IntegerField()),
                ('market_cap', models.BigIntegerField()),
                ('logo', models.URLField()),
                ('sector', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('buying_price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
