# Generated by Django 4.1.2 on 2023-08-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='change',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
    ]
